# --- docker-compose.yml ---
# Use this to spin up PostgreSQL
# Save this as docker-compose.yml in project root

 version: '3.8'
 services:
   postgres:
     image: postgres:15
     restart: always
     environment:
       POSTGRES_DB: tiktok_clone
       POSTGRES_USER: user
       POSTGRES_PASSWORD: password
     ports:
       - "5432:5432"
     volumes:
       - pgdata:/var/lib/postgresql/data

 volumes:
   pgdata: